### ISSUE TITLE
className Prop Doesn't work

### ISSUE THREAD

**Issue by Replobik** [cinderblock/react-smoothie#2]
Is there any props for styling chart with css?

**Comment by cinderblock** [comment]
Unfortunately, not really because *Smoothie Chart* handles all of the drawing in the canvas itself.

Effectively this component expands to a single `<canvas>` tag that *Smoothie Chart* uses to draw on.

Take a look at http://smoothiecharts.org/builder/ for Smoothie Chart's options for coloring your lines and such.

I just noticed the tooltip options which expect some css styles. Maybe this is what you're looking to edit? I have not looked at supporting the tooltip.
